version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: finebudget-db
    environment:
      POSTGRES_DB: finebudget
      POSTGRES_USER: finebudget
      POSTGRES_PASSWORD: finebudget123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: finebudget-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seqdata:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: finebudget-jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"

volumes:
  pgdata:
  seqdata: